### ISSUE TITLE
Packaging?

### ISSUE THREAD

**Issue by vsoch** [expfactory/expfactoryr#6]
hey @earcanal ! I'm developing some infrastructure for rOpenSci, and was wondering if I could use expfactoryr as a test package. It would mean adding it as a submodule to a repository, and then doing some trivial pushes / updates. Would that be okay with you?

**Comment by earcanal** [comment]
Does that mean it would move repo?

**Comment by vsoch** [comment]
Nope, stays right here! A submodule is a reference / link on GitHub to another location.

**Comment by earcanal** [comment]
Sounds fine with me.

Incidentally, I've found a cleaner way of silencing those `R CMD check` notes using `rlang::.data`. Here's [an example](https://github.com/earcanal/breath-counting-task/blob/earcanal/master/expfactory.breathcounting/R/expfactory.breathcounting.R).

**Comment by vsoch** [comment]
thanks :)
